name: build-pr
on:
 pull_request:
   types: [opened, synchronize, reopened, closed]
env:
  VERSION: 'undefined'
  TOKEN: ${{secrets.PAT}}
jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
  build-leia:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build addon
        run: $GITHUB_WORKSPACE/.github/scripts/build-addon.sh ${{ needs.versioning.outputs.VERSION }} Leia
      - name: Upload Addon-artifacts-Leia
        uses: actions/upload-artifact@v2
        with:
          name: Addon-artifacts-Leia
          path: "${{ runner.temp }}/Leia/*.zip"
  build-matrix:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build addon
        run: $GITHUB_WORKSPACE/.github/scripts/build-addon.sh ${{ needs.versioning.outputs.VERSION }} Matrix     
      - name: Upload Addon-artifacts-Matrix
        uses: actions/upload-artifact@v2
        with:
          name: Addon-artifacts-Matrix
          path: "${{ runner.temp }}/Matrix/*.zip"
