name: build-addon
on:
  push:
  schedule:
    - cron:  '0 0 * * SUN'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_NAME_PYTHON2: repository.sendtokodi
      REPO_URL_PYTHON2: "github.com/firsttris/repository.sendtokodi.git"
      REPO_NAME_PYTHON3: repository.sendtokodi.python3
      REPO_URL_PYTHON3: "github.com/firsttris/repository.sendtokodi.python3.git"
      VERSION: 0.1.${{github.run_id}}
      ADDON_NAME: plugin.video.sendtokodi
      NAME: sendtokodi
      TOKEN: ${{secrets.PAT}}
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: recursive 
      - run: git config --global user.email "tristanteufel@googlemail.com"
      - run: git config --global user.name "firsttris"    
      - run: chmod +x $GITHUB_WORKSPACE/.github/scripts/build-script.sh
      - run: $GITHUB_WORKSPACE/.github/scripts/build-script.sh $REPO_NAME_PYTHON2 $REPO_URL_PYTHON2
      - run: $GITHUB_WORKSPACE/.github/scripts/build-script.sh $REPO_NAME_PYTHON3 $REPO_URL_PYTHON3
